name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      BAZEL_USE_CPP_ONLY_TOOLCHAIN: 1

    steps:
    - uses: actions/checkout@v2

    - name: Mount Bazel Cache
      uses: actions/cache@v1
      with:
        path: .cache
        key: bazel-${{ matrix.os }}-${{ github.sha }}
        restore-keys: |
          bazel-${{ matrix.os }}

    - name: Configure Bazel
      run: |
        cat >.bazelrc.local <<EOF
        build --config=ci
        EOF

    - name: Install bazelisk
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        if [[ ${{ matrix.os }} = macos* ]]; then
          curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-darwin-amd64" -o "${GITHUB_WORKSPACE}/bin/bazel"
        else
          curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64" -o "${GITHUB_WORKSPACE}/bin/bazel"
        fi
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
        "${GITHUB_WORKSPACE}/bin/bazel" version

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //... \
          --execution_log_json_file=test_log_execution.json \
          --experimental_workspace_rules_log_file=test_log_workspace.pb

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...

    - name: Bundle Bazel Logs
      run: |
        tar czf test_logs_${{ matrix.os }}.tgz test_log_execution.json test_log_workspace.pb

    - uses: actions/upload-artifact@v1
      with:
        name: bazel-logs-${{ matrix.os }}
        path: test_logs_${{ matrix.os }}.tgz
