name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Mount Bazel Cache
      uses: actions/cache@v1
      with:
        path: .cache
        key: bazel-${{ github.sha }}
        restore-keys: |
          bazel-

    - name: Configure Bazel
      run: |
        cat >.bazelrc.local <<EOF
        build --config=ci
        EOF

    - name: Install bazelisk
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64" -o "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
        "${GITHUB_WORKSPACE}/bin/bazel" version

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...
